import discord
from discord import app_commands
from discord.ext import commands
from datetime import datetime
import random

class TriviaView(discord.ui.View):
    def __init__(self, interaction, correct_title, options):
        super().__init__(timeout=60)
        self.correct_title = correct_title
        self.interaction = interaction
        for option in options:
            self.add_item(TriviaButton(option, correct_title, interaction.user))

class TriviaButton(discord.ui.Button):
    def __init__(self, label, correct_title, requester):
        super().__init__(label=label, style=discord.ButtonStyle.primary)
        self.correct_title = correct_title
        self.requester = requester

    async def callback(self, interaction):
        if interaction.user.id != self.requester.id:
            await interaction.response.send_message("This isn't your trivia question.", ephemeral=True)
            return
        for child in self.view.children:
            child.disabled = True
        await interaction.response.edit_message(view=self.view)
        if self.label == self.correct_title:
            result = discord.Embed(title="Correct!", description=f"**{self.correct_title}** was the right answer.", color=discord.Color.green())
        else:
            result = discord.Embed(title="Incorrect!", description=f"The correct answer was **{self.correct_title}**.", color=discord.Color.red())
        await interaction.followup.send(embed=result, ephemeral=True)

trivia_data = [
    {"lyric": "I got it out the dirt like a zombie", "song": "From the dirt"},
    {"lyric": "I throw my money up, I throw my money up", "song": "I JUST BOUGHT A NEW NOSE!"},
    {"lyric": "I'm in the club and all I see is paparazzi", "song": "MAKE ME FAMOUS!"},
    {"lyric": "Slit my wrists and now I'm laughing, Ten racks, got my jeans saggin'", "song": "10k freestyle"},
    {"lyric": "American beauty queen, I got blood all on my jeans", "song": "American beauty"},
    {"lyric": "Take off that makeup, you're still fucking mid", "song": "American psycho"},
    {"lyric": "Slit my neck on Friday, I'm driving on the highway", "song": "Anorexic party"},
    {"lyric": "Can you close the curtains please? Come with me backstage", "song": "backstage"},
    {"lyric": "Beware of dog, I'm in the pound", "song": "beware of the dog"},
    {"lyric": "Shoot me in the heart, turn me to a star", "song": "Carrie white"},
    {"lyric": "Kill myself on my fuckin' birthday", "song": "Birthday song"},
    {"lyric": "Pop a Xan and pop a tag, backstage pass, we in the back", "song": "Bloodt Mary"},
    {"lyric": "You're like a snack, I just wanna eat you", "song": "Cookies are for Santa"},
    {"lyric": "Slit my neck, watch me bleed", "song": "Cut me from the frame"},
    {"lyric": "Pourin' blood up in the blunt, I told Kaleb spark me", "song": "Talk to the hand"},
    {"lyric": "You a goofy, you not bulletproof", "song": "Fuck the fame"},
    {"lyric": "Tie me to the train tracks, yeah, I really love that", "song": "Fuck ur clique"},
    {"lyric": "Be my beauty queen, I'll buy you anything", "song": "Elf on the shelf"},
    {"lyric": "Let's go shopping at the mall, buy everything", "song": "Crying in the club"},
    {"lyric": "Hop outside the limousine in the backseat of the cab", "song": "Bloodt Mary"},
    {"lyric": "I'm sendin' texts, like, are you up tonight?", "song": "love story"},
    {"lyric": "You're not my friend so don't act like it", "song": "haunted house"},
    {"lyric": "I just killed my ex today", "song": "Murder in Hollywood"},
    {"lyric": "I'm lost in the sauce", "song": "true love"},
    {"lyric": "We're moving in slow-mo, like a movie", "song": "Wickerr man"},
    {"lyric": "I don't have no fuckin' friends because I'm a scary guy", "song": "10k freestyle"},
    {"lyric": "Kiss me in the moonlight 'cause I'm motherfucking lit", "song": "10k freestyle"},
    {"lyric": "She got cuts all on her thighs, I got slits all on my wrists", "song": "10k freestyle"},
    {"lyric": "Die young, get cake, shoutout Lil Jeep", "song": "10k freestyle"},
    {"lyric": "I'ma fuck your skeleton, you can be my zombie wife", "song": "10k freestyle"},
    {"lyric": "Shoot me with a uzi, I'm covered in Gucci", "song": "American beauty"},
    {"lyric": "I got racks all on me, she's a broken barbie", "song": "American beauty"},
    {"lyric": "My bitch is a model, I feel fuckin' awful, Sippin' out the bottle", "song": "American beauty"},
    {"lyric": "Yeah, I'm a Jesus freak, so let's say a prayer", "song": "American beauty"},
    {"lyric": "Just lose your pants, bitch, I wanna dance, bitch", "song": "MAKE ME FAMOUS!"},
    {"lyric": "Let's go to the mall, spend it all, we'll buy it all", "song": "MAKE ME FAMOUS!"},
    {"lyric": "I know you want me, just drop that fucking bra", "song": "MAKE ME FAMOUS!"},
    {"lyric": "I feel like Punkinloveee but right now I'm the only one", "song": "MAKE ME FAMOUS!"},
    {"lyric": "No regrets bitch, let's get drunk at the outlets", "song": "MAKE ME FAMOUS!"},
    {"lyric": "Disney star, yeah, I just got signed, bruh", "song": "MAKE ME FAMOUS!"},
    {"lyric": "H-O-fuckin'-T, I'm in the limousine", "song": "MAKE ME FAMOUS!"},
    {"lyric": "Get away from me, get that opp away from me", "song": "MAKE ME FAMOUS!"},
    {"lyric": "I'ma slit your throat like Bianca", "song": "Bury me alive"},
    {"lyric": "New designer coat, I'm rockin' Prada", "song": "Bury me alive"},
    {"lyric": "And I don't want that ho, I want my momma", "song": "Bury me alive"},
    {"lyric": "Hop out the limousine, free Britney, I'm off Xanax like it's 2017", "song": "Bloodt Mary"},
    {"lyric": "Stomped his ass out, I got blood on my Nikes", "song": "Bloodt Mary"},
    {"lyric": "You can't be with me, you're ugly and you're fucking fat", "song": "City lights"},
    {"lyric": "I just wanted to see the Christmas lights", "song": "take a picture, it'll last longer"},
    {"lyric": "You're ugly and you're fucking fat", "song": "Christmas wishlist"},
    {"lyric": "Yeah, bad bitch on my right, bad bitch on my left", "song": "Anorexic party"},
    {"lyric": "She fuck me in the club, She fuck me in my Jordan 1s", "song": "Christmas wishlist"},
    {"lyric": "I swear I'm in a movie, American Beauty", "song": "Dead presidents"},
    {"lyric": "Be my zombie princess, we can watch the sunset", "song": "Hollywood dreams"},
    {"lyric": "Shoot me in the heart, turn me to a star", "song": "Carrie white"},
    {"lyric": "Let's go to Disneyland, let's go to the park", "song": "Carrie white"},
    {"lyric": "Fuck me in your wedding dress, marry me", "song": "Carrie white"},
    {"lyric": "I'm really hangin' from the Christmas tree, put a star on me", "song": "Carrie white"},
    {"lyric": "She wanna link but I don't know where she been", "song": "Elf on the shelf"},
    {"lyric": "I like your tank top, when it's see-through", "song": "Anorexic party"},
    {"lyric": "Drop racks on those titties bitch, Yo' shit look so mini, bitch", "song": "backstage"},
    {"lyric": "Like Jesus, take the wheel, I take pics on BeReal", "song": "Anorexic party"},
    {"lyric": "I'm hitting on my ex, like, \"Can you please come back?\"", "song": "Picture perfect"},
    {"lyric": "I keep it rare, yeah, like a drum kit", "song": "Picture perfect"},
    {"lyric": "I don't fuck with candy corn, put me in a fuckin' porn", "song": "Bloodt Mary"},
    {"lyric": "Cameras in my face, paparazzi know my name", "song": "Demon with a halo"},
    {"lyric": "Shoot me with a fuckin' Uzi, turn me to a smoothie", "song": "Demon with a halo"},
    {"lyric": "She sex me up on Discord", "song": "Every day is Halloween 2"},
    {"lyric": "I unfollowed everyone, So everyone get off my dick", "song": "Every day is Halloween 2"},
    {"lyric": "Kill cheerleaders, fuck my teachers", "song": "Dead presidents"},
    {"lyric": "I'm eatin' flesh, bitch, and I love it", "song": "Dead presidents"},
    {"lyric": "George Washington, I'm a money fiend", "song": "Dead presidents"},
    {"lyric": "Let's hit the bar, they don't card", "song": "Black amiri Uggs"},
    {"lyric": "I'm flexing hard, I'll never stop", "song": "Black amiri Uggs"},
    {"lyric": "I love dirty Sprite and I love cough drops", "song": "lean"},
    {"lyric": "I bought a nose, I need rhinoplasty", "song": "Black amiri Uggs"},
    {"lyric": "Slit my wrists, suicide, married to my zombie wife", "song": "Welcome to my show"},
    {"lyric": "Dancin' with a kitchen knife, kiss me under Christmas lights", "song": "Welcome to my show"},
    {"lyric": "I'm real Prada gothic, if you're on it then I'm on it, bitch", "song": "Welcome to my show"},
    {"lyric": "I just coughed a Xan up, got it fuckin' with my stomach", "song": "Welcome to my show"},
    {"lyric": "I'm ugly anorexic, you can kiss my skeleton", "song": "Welcome to my show"},
    {"lyric": "Glock in my Jan sport, shout out zak hilton", "song": "Welcome to my show"},
    {"lyric": "I'ma piss on your tombstone, WE'RE ALL IN LOVE, we do the most", "song": "Welcome to my show"},
    {"lyric": "Smokin' dope, indica, there's a party, shoot it up", "song": "Welcome to my show"},
    {"lyric": "Why they gay? Why they on my dick?", "song": "Bloodt Mary"},
    {"lyric": "I just killed my ex today", "song": "Murder in Hollywood"},
    {"lyric": "You're not my friend so don't act like it", "song": "haunted house"},
    {"lyric": "Tattooed in the club, what is going on right now?", "song": "Ugly & Glamorous"},
    {"lyric": "Drop that bra and show some tits", "song": "Ugly & Glamorous"},
    {"lyric": "Cuddle me like a bunny", "song": "Circus freak"},
    {"lyric": "I just popped a thousand Xanax, I feel ugly", "song": "Circus freak"},
    {"lyric": "I'm in the hospital on life support, unplug me", "song": "Circus freak"},
    {"lyric": "I'm a sketchy guy, you might lose your fuckin' life", "song": "White girl wednesday"},
    {"lyric": "Let's have sex at the mall, yeah, you turn me on", "song": "CAMERAS POINTED AT ME!"},
    {"lyric": "I'm off fuckin' lean, bitch, just like Lil Wayne", "song": "Giving girls cocaine"},
    {"lyric": "Cookies on my plate, I'm in love with these candy canes", "song": "Prada"},
    {"lyric": "I'll grow antlers and I'll turn into a reindeer", "song": "Prada"},
    {"lyric": "You're a thot and it shows, You are fat and you're old", "song": "Kms on Xmas"},
    {"lyric": "I'm posted at McDonald's lookin' for Grimace", "song": "rare Xmas freestyle"},
    {"lyric": "I pass that bitch to Brayden 'cause she's a groupie", "song": "rare Xmas freestyle"},
    {"lyric": "You're acting like a bitch just so you know", "song": "rare Xmas freestyle"},
    {"lyric": "Let's go to the moon, yeah, I'll take you to the stars", "song": "SCARYY PARTYY"},
    {"lyric": "I'm an ugly vamp flexed up in the moonlight", "song": "SCARYY PARTYY"},
    {"lyric": "I'm sendin' texts, like, are you up tonight?", "song": "love story"},
    {"lyric": "Yeah, I'm barkin' like a dog, yeah, beware", "song": "American beauty"},
    {"lyric": "On Sunday, I'm not a sinner", "song": "Elf on the shelf"},
    {"lyric": "I rap, I'm not a singer", "song": "Elf on the shelf"},
    {"lyric": "You make me fucking sick, you make me wanna die", "song": "Christmas lights"},
    {"lyric": "I'm so H-O-T on MTV", "song": "I JUST BOUGHT A NEW NOSE!"},
    {"lyric": "She's in Abercrombie, be my paparazzi", "song": "I JUST BOUGHT A NEW NOSE!"},
    {"lyric": "I'm at the pumpkin patch, where's Punkin at?", "song": "Bloodt Mary"},
    {"lyric": "She's a slut, so I'm finna show her love", "song": "Birthday song"},
    {"lyric": "I'm a Jesus freak with a Jesus piece on my chain", "song": "Merry go round"},
    {"lyric": "I don't have no fuckin' friends because I'm a scary guy", "song": "10k freestyle"},
    {"lyric": "Fuck me in your wedding dress, marry me", "song": "Carrie white"},
    {"lyric": "I sold myself to the Devil, Now labels wanna sign me", "song": "Every day is Halloween"},
    {"lyric": "I was lying in the dirt with the rest of my zombies", "song": "Every day is Halloween"},
    {"lyric": "Take off that makeup, you're still fucking mid", "song": "American psycho"},
    {"lyric": "I'll be famous when they find out what I did", "song": "American psycho"},
    {"lyric": "I like your tank top, when it's see-through", "song": "Anorexic party"},
    {"lyric": "Slit my neck on Friday, I'm driving on the highway", "song": "Anorexic party"},
    {"lyric": "Like Jesus, take the wheel, I take pics on BeReal", "song": "Anorexic party"},
    {"lyric": "You're big like a seal, hang myself on IG reels", "song": "Anorexic party"},
    {"lyric": "We should break up, I think that we should just be friends", "song": "Anorexic party"},
    {"lyric": "I'm in Hollywood for my show", "song": "City lights"},
    {"lyric": "You look great when you put on that new Chanel", "song": "City lights"},
    {"lyric": "Like bitch, I'm Nick, it's nice to meet you", "song": "City lights"},
    {"lyric": "They on my dick, like, what the fuck is new?", "song": "City lights"},
    {"lyric": "You can't get close to me, we not personal", "song": "City lights"},
    {"lyric": "Let's go shopping at the mall, buy everything", "song": "Crying in the club"},
    {"lyric": "I'm sorry that I care, I'm sorry that you never did", "song": "Crying in the club"},
    {"lyric": "You're all I ever wanted, throw me in the garbage", "song": "Crying in the club"},
    {"lyric": "Hit my Motorola phone", "song": "Crying in the club"},
    {"lyric": "There's a dance tonight, baby, if you wanna go", "song": "Crying in the club"},
    {"lyric": "Pourin' blood up in the blunt, I told Kaleb spark me", "song": "Talk to the hand"},
    {"lyric": "Candy corn all on me, dirty-pop army", "song": "Talk to the hand"},
    {"lyric": "Dirty pop, killing cops, don't act like me 'cause you're not", "song": "Talk to the hand"},
    {"lyric": "I'm makin' bloody racks, we gon' rob your mans", "song": "Talk to the hand"},
    {"lyric": "We gon' steal chain, chain swing, Dirty pop wedding ring", "song": "Talk to the hand"},
    {"lyric": "Slit my wrists in the sink, I can't see shit, I can't think", "song": "Talk to the hand"},
    {"lyric": "Greetings and salutations", "song": "Faceless"},
    {"lyric": "Kill you and make it look like suicide", "song": "Faceless"},
    {"lyric": "Know your place before you get erased", "song": "Faceless"},
    {"lyric": "I'm dead on fuckin' pavement", "song": "Faceless"},
    {"lyric": "New year, new me, got blood on my jeans, on TV screens", "song": "Hollywood dreams"},
    {"lyric": "Bad bitch on me, She's from the scene", "song": "Hollywood dreams"},
    {"lyric": "Bloody jeans and scary dreams, put me in a movie scene", "song": "Hollywood dreams"},
    {"lyric": "Cameras pointed right at me, I just wanna hear you scream", "song": "Hollywood dreams"},
    {"lyric": "Put me down like a dog, Kiss me, princess, I'm a frog", "song": "Nervous wreck"},
    {"lyric": "You're a fraud, you're not dirty pop", "song": "Nervous wreck"},
    {"lyric": "I just stole all your shit like I am The Grinch", "song": "Nervous wreck"},
    {"lyric": "And you know I'm walkin', yeah, I'm walkin' with a 6", "song": "Nervous wreck"},
    {"lyric": "I just hit the bank in my Air Force 1's", "song": "No Russian"},
    {"lyric": "My cup full of dirt, the mud is what I love", "song": "No Russian"},
    {"lyric": "You're like a snack, I just wanna eat you", "song": "Cookies are for Santa"},
    {"lyric": "I looked inside the mirror, I saw a monster", "song": "Cookies are for Santa"},
    {"lyric": "It's all CGI like a movie", "song": "Cookies are for Santa"},
    {"lyric": "I have a bag full of goodies", "song": "Cookies are for Santa"},
    {"lyric": "I'm getting drunk, I'm getting, getting drunk", "song": "Undead bride"},
    {"lyric": "It's an act, I don't know how to feel", "song": "Undead bride"},
    {"lyric": "Caught him slippin' like banana peel, You are big, big like a seal", "song": "Undead bride"},
    {"lyric": "I'm dancing like a ballerina", "song": "Undead bride"},
    {"lyric": "And I can't see because everything is foggy", "song": "Undead bride"},
    {"lyric": "I got two sticks and it's like I'm playing hockey", "song": "Undead bride"},
    {"lyric": "I'm all dolled up, I don't give a fuck", "song": "Undead bride"},
    {"lyric": "Be my beauty queen, I'll buy you anything", "song": "Elf on the shelf"},
    {"lyric": "If I pull up to your door, you know I'm not finna knock", "song": "Elf on the shelf"},
    {"lyric": "Why did everything start going wrong again?", "song": "White girl wednesday"},
    {"lyric": "She's a lightskin, you know I like that mix", "song": "Kick the cup"},
    {"lyric": "She said she can feel my dick, it's just my blick", "song": "Kick the cup"},
    {"lyric": "If we're not friends, you can't use my name", "song": "Kick the cup"},
    {"lyric": "I love America, I'ma rip your face off", "song": "Giving girls cocaine"},
    {"lyric": "I keep it rare, yeah, like a drum kit", "song": "Picture perfect"},
    {"lyric": "I'm dirty, and I'm icy, they can't do it like me", "song": "Ugly & Glamorous"},
    {"lyric": "I'm lost in the sauce", "song": "true love"},
    {"lyric": "You're ugly and you're fucking fat", "song": "Christmas wishlist"},
    {"lyric": "I unfollowed everyone because I don't give a fuck", "song": "I JUST BOUGHT A NEW NOSE!"},
    {"lyric": "Party like it's 2012, I got Bacardi in my cup", "song": "I JUST BOUGHT A NEW NOSE!"},
    {"lyric": "I feel like Punkinloveee but right now I'm the only one", "song": "MAKE ME FAMOUS!"},
    {"lyric": "Omg, Z.B.C. hate me", "song": "MAKE ME FAMOUS!"},
    {"lyric": "Get away from me, get that opp away from me", "song": "MAKE ME FAMOUS!"},
    {"lyric": "Every day is Halloween, like a pumpkin, bitch, I'm lit", "song": "10k freestyle"},
    {"lyric": "They tryna act like WE'RE ALL IN LOVE, but you are not", "song": "10k freestyle"},
    {"lyric": "My bitch is a model, I feel fuckin' awful, Sippin' out the bottle", "song": "American beauty"},
    {"lyric": "I got racks all on me, she's a broken barbie", "song": "American beauty"},
    {"lyric": "New designer coat, I'm rockin' Prada", "song": "Bury me alive"},
    {"lyric": "And I don't want that ho, I want my momma", "song": "Bury me alive"},
    {"lyric": "Let's go to the mall, spend it all, we'll buy it all", "song": "MAKE ME FAMOUS!"},
    {"lyric": "I'm so H-O-T on MTV", "song": "I JUST BOUGHT A NEW NOSE!"},
    {"lyric": "Disney star, yeah, I just got signed, bruh", "song": "MAKE ME FAMOUS!"},
    {"lyric": "Rapunzel, let down your long hair", "song": "American beauty"},
    {"lyric": "Yeah, I'm a Jesus freak, so let's say a prayer", "song": "American beauty"},
    {"lyric": "Starve myself, I can weigh less", "song": "American psycho"},
    {"lyric": "Dead opps on the floor at the cemetery", "song": "Birthday song"},
    {"lyric": "Put me on the news, now the rumors are true", "song": "Birthday song"},
    {"lyric": "I got bloody racks on me, I'm off dirty drugs", "song": "Bloodt Mary"},
    {"lyric": "Pop a Xan' and fall asleep, honestly, we're meant to", "song": "Bloodt Mary"},
    {"lyric": "Thirty racks all on my jeans, I'm off the lean inside the jeep", "song": "Bloodt Mary"},
    {"lyric": "I can't be with you, you're ugly and you get around", "song": "Anorexic party"},
    {"lyric": "Just lose your pants, bitch, I wanna dance, bitch", "song": "MAKE ME FAMOUS!"},
    {"lyric": "No regrets bitch, let's get drunk at the outlets", "song": "MAKE ME FAMOUS!"},
    {"lyric": "I throw my money up, I throw my money up", "song": "I JUST BOUGHT A NEW NOSE!"},
    {"lyric": "Kiss me in the moonlight 'cause I'm motherfucking lit", "song": "10k freestyle"},
    {"lyric": "She got cuts all on her thighs, I got slits all on my wrists", "song": "10k freestyle"},
    {"lyric": "Shoot me with a uzi, I'm covered in Gucci", "song": "American beauty"},
    {"lyric": "Shoot me in the heart, turn me to a star", "song": "Carrie white"},
    {"lyric": "Let's go to Disneyland, let's go to the park", "song": "Carrie white"},
    {"lyric": "No security, I pull up with my gun", "song": "Carrie white"},
    {"lyric": "Why you tryna play me like a puppet?", "song": "Carrie white"},
    {"lyric": "You really make me nervous, butterflies", "song": "Carrie white"},
    {"lyric": "I really wanna hold you 'til you die", "song": "Carrie white"},
    {"lyric": "New Chanel with the pink Burberry", "song": "Carrie white"},
    {"lyric": "I'm really hangin' from the Christmas tree, put a star on me", "song": "Carrie white"},
    {"lyric": "Trick or Treat, smell my feet, Give me something good to eat", "song": "Masquerade"},
    {"lyric": "Who put drugs beneath the Christmas tree? Now I'm crying", "song": "Masquerade"},
    {"lyric": "Did you know I liked that? 'Cause I really like that", "song": "Masquerade"},
    {"lyric": "Bury me alive, I just wanna cry", "song": "Merry go round"},
    {"lyric": "Like a fuckin' dog? I'm a motherfuckin' hound", "song": "Merry go round"},
    {"lyric": "Cardi B, Ice Spice, will you be my zombie wife?", "song": "Merry go round"},
    {"lyric": "I'm dancin' in puddles, I'm dancing in the fuckin' rain", "song": "Merry go round"},
    {"lyric": "I'm a Jesus freak with a Jesus piece on my chain", "song": "Merry go round"},
    {"lyric": "It's WE'RE ALL IN LOVE in the club, They wanna be like me, they wanna be like us", "song": "Merry go round"},
    {"lyric": "I just coughed a Xan up, got it fuckin' with my stomach", "song": "Welcome to my show"},
    {"lyric": "Glock in my Jan sport, shout out zak hilton", "song": "Welcome to my show"},
    {"lyric": "I'ma piss on your tombstone, WE'RE ALL IN LOVE, we do the most", "song": "Welcome to my show"},
    {"lyric": "Smokin' dope, indica, there's a party, shoot it up", "song": "Welcome to my show"},
    {"lyric": "I'm rappin' like I'm Lone or Diamondsonmydick", "song": "Fuck ur clique"},
    {"lyric": "WE'RE ALL IN LOVE for life, so it's fuck your clique", "song": "Fuck ur clique"},
    {"lyric": "Carve my name in your skin if you want me, bitch", "song": "Fuck ur clique"},
    {"lyric": "I really woke up, pissed off, You could really die tonight, like King Von", "song": "Xanax underneath the christmas tree"},
    {"lyric": "You could really pull up, I got that shit on me", "song": "Xanax underneath the christmas tree"},
    {"lyric": "You're big like a seal, hang myself on IG reels", "song": "Anorexic party"},
    {"lyric": "Take you to the moon, yeah, I'll take you to the stars", "song": "SCARYY PARTYY"},
    {"lyric": "Dancin' with a kitchen knife, kiss me under Christmas lights", "song": "Welcome to my show"},
    {"lyric": "Slit wrists, suicide, married to my zombie wife", "song": "Welcome to my show"},
    {"lyric": "I'm flexing hard, I'll never stop", "song": "Black amiri Uggs"},
    {"lyric": "Tie me to the train tracks, yeah, I really love that", "song": "Fuck ur clique"},
    {"lyric": "Let's hit the bar, they don't card", "song": "Black amiri Uggs"},
    {"lyric": "I got no presents on Christmas", "song": "Black amiri Uggs"},
    {"lyric": "Six ninety on my shoes, what do I have to lose?", "song": "Black amiri Uggs"},
    {"lyric": "Cookies on my plate, I'm in love with these candy canes", "song": "Prada"},
    {"lyric": "The South Pole is my favorite place", "song": "Prada"},
    {"lyric": "I'll grow antlers and I'll turn into a reindeer", "song": "Prada"},
    {"lyric": "I take shots, I don't fuck with beer", "song": "Prada"},
    {"lyric": "I'm sendin' texts, like, are you up tonight?", "song": "love story"},
    {"lyric": "I'm posted at McDonald's lookin' for Grimace", "song": "rare Xmas freestyle"},
    {"lyric": "Bullets to my head just like Nirvana", "song": "rare Xmas freestyle"},
    {"lyric": "I'm like an ornament, I'm even hanging from the tree", "song": "rare Xmas freestyle"},
    {"lyric": "I pass that bitch to Brayden 'cause she's a groupie", "song": "rare Xmas freestyle"},
    {"lyric": "Damn bruh, I just got my fucking bands up, like, who are ya?", "song": "Hang with me"},
    {"lyric": "She listen like a bitch, all black on my fit", "song": "Hang with me"},
    {"lyric": "Cash, racks, something you don't know", "song": "Hang with me"},
    {"lyric": "Money, bands, go get some fuckin' hoes", "song": "Hang with me"},
    {"lyric": "Don't talk to me, bitch, talk to the hand", "song": "Hang with me"},
    {"lyric": "If it ain't 'bout money, I don't give a fuck", "song": "Hang with me"},
    {"lyric": "I saw her backstage, she gave me a hug", "song": "Hang with me"},
    {"lyric": "I fucked your mother, shout out young w6lker", "song": "Don't touch me, I'm expensive"},
    {"lyric": "She's a slut, so I'm finna show her love", "song": "Birthday song"},
    {"lyric": "Be the Blaire to my Chuck, you could get hit with this pump", "song": "Welcome to my show"},
    {"lyric": "I'm ugly anorexic, you can kiss my skeleton", "song": "Welcome to my show"},
    {"lyric": "Shoot me with a fuckin' Uzi, turn me to a smoothie", "song": "Demon with a halo"},
    {"lyric": "Cameras in my face, paparazzi know my name", "song": "Demon with a halo"},
    {"lyric": "I don't love you, bitch, I love these fuckin' racks", "song": "Put you on"},
    {"lyric": "I got so rich so quick, your welfare check is coming in", "song": "Bible school"},
    {"lyric": "Jesus freak, I rock my piece and I won't ever sin", "song": "Bible school"},
    {"lyric": "My mommy love me, bitches wanna hug me", "song": "Bible school"},
    {"lyric": "There's blow up in my nose, I'm sniffin' fuckin' snow globes", "song": "Bible school"},
    {"lyric": "Pourin' blood up in the blunt, I told Kaleb spark me", "song": "Talk to the hand"},
    {"lyric": "Candy corn all on me, dirty-pop army", "song": "Talk to the hand"},
    {"lyric": "Dirty pop, killing cops, don't act like me 'cause you're not", "song": "Talk to the hand"},
    {"lyric": "I'm makin' bloody racks, we gon' rob your mans", "song": "Talk to the hand"},
    {"lyric": "We gon' steal chain, chain swing, Dirty pop wedding ring, Slit my wrists in the sink, I can't see shit, I can't think", "song": "Talk to the hand"},
    {"lyric": "I just wanted to see the Christmas lights", "song": "take a picture, it'll last longer"},
    {"lyric": "I sold like ten pills and laced them all with fent", "song": "take a picture, it'll last longer"},
    {"lyric": "You can hit my juul like we are in school", "song": "Shooting star"},
    {"lyric": "I'm shooting at the hearse, a hundred for a verse", "song": "Shooting star"},
    {"lyric": "That boy finna fold, just like laundry", "song": "Shooting star"},
    {"lyric": "I'm feeling up her skirt, it's like a tsunami", "song": "Shooting star"},
    {"lyric": "You're acting like a bitch just so you know", "song": "rare Xmas freestyle"},
    {"lyric": "Devil to my left, God to my right", "song": "Picture perfect"},
    {"lyric": "I'm at my funeral and I see confetti", "song": "Picture perfect"},
    {"lyric": "I wanna see you in all black for our wedding", "song": "Picture perfect"},
    {"lyric": "I just killed my ex today", "song": "Murder in Hollywood"},
    {"lyric": "You're not my friend so don't act like it", "song": "haunted house"},
    {"lyric": "I wanna see you get undressed, get undressed for me, I'm starin' like Paparazzi", "song": "haunted house"},

]


song_titles = list(set([entry['song'] for entry in trivia_data]))

def setup(bot):
    @bot.tree.command(name="nick6383trivia", description="Guess which song a Nick6383 lyric comes from.")
    async def nick6383trivia(interaction):
        question = random.choice(trivia_data)
        lyric = question['lyric']
        correct = question['song']
        choices = [correct] + random.sample([s for s in song_titles if s != correct], 3)
        random.shuffle(choices)
        embed = discord.Embed(title="Trivia", description=f"*{lyric}*", color=discord.Color.from_rgb(255, 105, 180))
        year = datetime.now().year
        embed.set_footer(text=f"WE'RE ALL IN LOVE {year}")
        view = TriviaView(interaction, correct, choices)
        await interaction.response.send_message(embed=embed, view=view)
